import * as assert from 'assert';
import { splitByHeaders, createIndexFile } from './utils';

describe('splitByHeaders', () => {
    it('should return original content when there are no headers', () => {
        const content = 'Just some plain text.\nAnother line.';
        const result = splitByHeaders(content);
        // Each line gets a trailing newline appended during processing
        assert.deepStrictEqual(result, ['Just some plain text.\nAnother line.\n']);
    });

    it('should split content by h1 to h6 headers', () => {
        const content = '# Title\nBody1\n## Subtitle\nBody2\n### H3\nBody3\n#### H4\nBody4\n##### H5\nBody5\n###### H6\nBody6';
        const result = splitByHeaders(content);
        assert.strictEqual(result.length, 6);
        assert.ok(result[0].includes('# Title'));
        assert.ok(result[1].includes('## Subtitle'));
        assert.ok(result[2].includes('### H3'));
        assert.ok(result[3].includes('#### H4'));
        assert.ok(result[4].includes('##### H5'));
        assert.ok(result[5].includes('###### H6'));
    });

    it('should not split on lines that look like headers but are not', () => {
        const content = '#NotAHeader\nSome text\n##AlsoNotAHeader';
        const result = splitByHeaders(content);
        assert.strictEqual(result.length, 1);
        assert.ok(result[0].includes('#NotAHeader'));
    });

    it('should preserve trailing newlines in sections', () => {
        const content = '# Header\nLine1\nLine2';
        const result = splitByHeaders(content);
        assert.strictEqual(result.length, 1);
        assert.ok(result[0].endsWith('\n'));
    });
});

describe('createIndexFile', () => {
    it('should create index content for multiple parts', () => {
        const content = createIndexFile('doc.md', 3, 'doc');
        assert.ok(content.includes('# doc.md - Document Index'));
        assert.ok(content.includes('split into 3 parts'));
        assert.ok(content.includes('[Part 1](./doc_part1.md)'));
        assert.ok(content.includes('[Part 2](./doc_part2.md)'));
        assert.ok(content.includes('[Part 3](./doc_part3.md)'));
    });

    it('should include auto-generated footer', () => {
        const content = createIndexFile('doc.md', 2, 'doc');
        assert.ok(content.includes('automatically generated by DocuGenius'));
    });
});
